steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/sampleweb:tag1 .
  automapSubstitutions: true

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - us-central1-docker.pkg.dev/${PROJECT_ID}/quickstart-docker-repo/sampleweb:tag1
